/* U03 · Unix shell, file system, redirection, globbing, regex, $PATH, environment
   (CL01/RD00, CL03/RD02, CL05, CL11/RD10) */
(function () {
  var h = Mastery.h;
  var CPROG = "cat > p.c <<'EOF2'\n#include <stdio.h>\nint main(){printf(\"ok\\n\");fprintf(stderr,\"bad\\n\");}\nEOF2\ncc -w -o p p.c\n";
  Mastery.unit({
    id: 'u03', title: 'Unix shell, redirection, globbing & $PATH', short: 'Shell & Unix',
    blurb: 'The file system tree, paths, core commands, the three standard streams, pipes, globbing vs regex, how commands are found, and environment variables.',
    lessons: [{ id: 'l1', label: 'CL01 \u00B7 Unix Basics' }, { id: 'l3', label: 'CL03 \u00B7 I/O, Pipes & Strings' }, { id: 'l5', label: 'CL05 \u00B7 $PATH, Globbing & Regex' }, { id: 'l17', label: 'CL11 \u00B7 Shell Config & Env Vars' }],
    learn: {
      big: [
        'The <b>shell</b> (bash) interprets your commands; the terminal only displays text. The shell does <b>expansion before the program runs</b>: globs, <code>$VAR</code> and <code>~</code> are replaced first, and the program sees only the result.',
        'Every process has three streams: <b>0 stdin</b>, <b>1 stdout</b>, <b>2 stderr</b>. <code>&gt;</code> overwrites, <code>&gt;&gt;</code> appends, <code>2&gt;</code> redirects stderr, <code>&lt;</code> feeds stdin, and <code>|</code> connects one command\u2019s stdout to the next one\u2019s stdin (no file).',
        '<b>Globbing</b> (shell, matches <i>filenames</i>): <code>*</code> any run, <code>?</code> exactly one char, <code>[abc]</code>/<code>[a-z]</code> one of a set. <b>Regex</b> (a program like grep, matches <i>text</i>) adds <code>+ ? {n,m} ^ $</code> and needs <code>.*</code> for \u201Cany run.\u201D',
        'Typing a command name makes the shell search <code>$PATH</code> (colon-separated) <b>left to right, first match wins</b>. The current directory is not searched, hence <code>./prog</code>.',
        'A variable is visible to child processes only if <b>exported</b>. Use <code>$VAR</code> to expand, and <code>${VAR}</code> when text follows the name.',
        'Absolute paths start at <code>/</code>; everything else is relative to the current directory. <code>.</code> is here, <code>..</code> is the parent, <code>~</code> is home. <code>rm</code> has no undo.'
      ],
      traps: [
        'Re-running a command with <code>&gt;</code> destroys the previous output. Use <code>&gt;&gt;</code> to keep it.',
        'Setting <code>PATH=\u201C/some/dir\u201D</code> <b>replaces</b> it. Append with <code>PATH=\u201C$PATH:/some/dir\u201D</code> or every command disappears.',
        '<code>*</code> means different things: alone in a glob it is \u201Cany characters\u201D; in a regex it means \u201Czero or more of the previous thing.\u201D',
        '<code>NAME=x</code> without <code>export</code> is invisible to a child shell or program.',
        '<code>find -name</code> takes a <b>glob</b>, not a regex. Quote it so the shell does not expand it first.'
      ],
      examples: [
        { kind: 'worked', title: 'What does <code>ls lab?.c</code> do when the directory holds <code>lab0.c  lab10.c  lab.c  labX.c</code>?',
          steps: [
            ['1', 'The <b>shell</b> sees <code>lab?.c</code> and expands it <i>before</i> <code>ls</code> runs.', 'Globs are filenames-matching by the shell, not by ls.'],
            ['2', '<code>?</code> must match <b>exactly one</b> character between <code>lab</code> and <code>.c</code>.', 'Zero characters or two characters both fail.'],
            ['3', 'Matches: <code>lab0.c</code> (\u201C0\u201D), <code>labX.c</code> (\u201CX\u201D). Not <code>lab.c</code> (zero) or <code>lab10.c</code> (two).', 'Check every candidate against the one-character rule.'],
            ['4', '<code>ls</code> receives <code>lab0.c labX.c</code> as two ordinary arguments.', 'The program never sees the pattern.']
          ], takeaway: 'Expand the pattern against the real filenames yourself, one candidate at a time. The shell does the matching, the command only gets the result.' },
        { kind: 'complete', item: h.mem('glob character class', 'Same files plus <code>lab1.c</code>. What does <code>echo lab[01]*.c</code> print? Fill in which of the five files match (yes/no).', '', [['lab0.c', 'yes', 'given'], ['lab1.c', 'yes'], ['lab10.c', 'yes'], ['lab.c', 'no'], ['labX.c', 'no']], '<code>[01]</code> is exactly one char, 0 or 1; then <code>*</code> takes any run (including empty); then <code>.c</code>. lab10.c: 1, then \u201C0\u201D from *, then .c. lab.c has no char for <code>[01]</code>; labX.c has X, which is not 0 or 1.', { verify: { sh: 'touch lab0.c lab1.c lab10.c lab.c labX.c\nfor f in lab0.c lab1.c lab10.c lab.c labX.c; do case "$f" in lab[01]*.c) echo yes;; *) echo no;; esac; done', expect: ['yes', 'yes', 'yes', 'no', 'no'] } }) },
        { kind: 'solo', item: h.mem('PATH search order', 'You have an executable <code>foo</code> in both <code>/tmp/x</code> (prints \u201Cx\u201D) and <code>/tmp/y</code> (prints \u201Cy\u201D). What does typing <code>foo</code> print when <code>PATH=/tmp/y:/tmp/x:/usr/bin</code>? And with <code>PATH=/tmp/x:/tmp/y:/usr/bin</code>?', '', [['PATH=y:x:\u2026', 'y'], ['PATH=x:y:\u2026', 'x']], 'The shell searches left to right and stops at the first match, so whichever directory is listed first wins.', { verify: { sh: 'mkdir x y; printf "#!/bin/sh\\necho x\\n" > x/foo; printf "#!/bin/sh\\necho y\\n" > y/foo; chmod +x x/foo y/foo\nPATH="$PWD/y:$PWD/x:$PATH" foo\nPATH="$PWD/x:$PWD/y:$PATH" foo', expect: ['y', 'x'] } }) }
      ]
    },
    cards: [
      ['Terminal vs shell vs CLI?', 'Terminal = the window/app that shows text. Shell (bash) = the program that interprets and runs commands. CLI = the text-based <i>style</i> of interaction.'],
      ['Absolute vs relative path?', 'Absolute starts at <code>/</code>. Relative starts from the current working directory. <code>.</code> here, <code>..</code> parent, <code>~</code> home.'],
      ['<code>cp</code> vs <code>mv</code>?', 'cp leaves the source and makes a copy. mv removes it from the old place (and is also how you rename). Neither changes your cwd.'],
      ['<code>rmdir</code> vs <code>rm -r</code>?', 'rmdir only removes an <i>empty</i> directory (a safety net). <code>rm -r</code> removes a directory and everything in it, with no undo.'],
      ['The three standard streams?', '0 = stdin (keyboard), 1 = stdout, 2 = stderr (both terminal by default).'],
      ['<code>&gt;</code> vs <code>&gt;&gt;</code> vs <code>2&gt;</code> vs <code>&lt;</code>?', '<code>&gt;</code> overwrite stdout to a file \u00B7 <code>&gt;&gt;</code> append \u00B7 <code>2&gt;</code> redirect stderr \u00B7 <code>&lt;</code> read stdin from a file.'],
      ['What does <code>a | b</code> do?', 'Connects a\u2019s stdout directly to b\u2019s stdin. No file is written.'],
      ['Which stream do <code>printf</code>/<code>putchar</code> write to? How do you write to stderr?', 'stdout always. Use <code>fprintf(stderr, ...)</code> or <code>fputc(c, stderr)</code>.'],
      ['Glob wildcards?', '<code>*</code> any run (incl. empty) \u00B7 <code>?</code> exactly one char \u00B7 <code>[abc]</code> one of the set \u00B7 <code>[a-z]</code> a range.'],
      ['Who evaluates a glob? A regex?', 'A glob is expanded by the <b>shell</b> against filenames, before the command runs. A regex is evaluated by a <b>program</b> (grep) against text.'],
      ['Regex pieces: <code>^ $ * + ? {n,m}</code>', 'start of line \u00B7 end of line \u00B7 zero or more \u00B7 one or more \u00B7 zero or one \u00B7 between n and m of the previous thing. \u201CAny run\u201D is <code>.*</code>.'],
      ['How does the shell find a command?', 'It searches each directory in <code>$PATH</code> (colon-separated), left to right, first match wins. The current directory is not searched.'],
      ['Why do you type <code>./prog</code>?', '<code>.</code> is not on $PATH (deliberately, so a rogue file named <code>ls</code> cannot hijack the real one). <code>./</code> names the file explicitly.'],
      ['Make a shell variable visible to child processes?', '<code>export VAR</code> (or <code>export VAR=value</code>). Plain assignment is not inherited.'],
      ['<code>$VAR</code> vs <code>${VAR}</code> vs <code>VAR</code>?', '<code>VAR</code> is the literal text. <code>$VAR</code> expands. <code>${VAR}</code> expands with explicit boundaries, needed when text follows (<code>${VAR}file</code>).']
    ],
    tiers: {
      recognize: [
        h.mc('absolute paths', 'Which of these is an <b>absolute</b> path?', [['<code>lab1/main.c</code>', 'No leading <code>/</code>, so it is relative to the current directory.'], '<code>/home/student/lab1/main.c</code>', ['<code>../lab1</code>', '<code>..</code> means \u201Cparent of where I am\u201D, so it is relative.'], ['<code>./lab1</code>', '<code>.</code> means the current directory, so this is relative.']], 1, 'An absolute path starts at the root <code>/</code> and means the same thing from anywhere.'),
        h.mc('overwrite vs append', 'You run <code>./run &gt; log.txt</code> twice. What does <code>log.txt</code> contain?', ['Only the output of the second run', ['The output of both runs, one after the other', 'That is what <code>&gt;&gt;</code> does. A single <code>&gt;</code> truncates the file first.'], ['An error, because the file already exists', 'The shell silently overwrites an existing file.'], ['Only the output of the first run', 'The second run reopens the file and truncates it.']], 0, '<code>&gt;</code> truncates then writes; <code>&gt;&gt;</code> appends.'),
        h.mc('why ./', 'You compile to <code>hello</code> in your current directory and type <code>hello</code>. The shell says \u201Ccommand not found.\u201D Why?', ['The current directory is not on $PATH, so the shell never looks there', ['gcc did not create the file', 'The file exists; the shell just never searches for it there.'], ['The file is not marked executable', 'gcc sets that bit; the failure is about <i>searching</i>, not permissions.'], ['bash only runs files ending in .out', 'File names do not matter; the search path does.']], 0, 'Type <code>./hello</code> to name the file explicitly.'),
        h.mc('who evaluates', 'Who interprets the pattern in <code>ls *.c</code> versus <code>grep \'^a.*z$\' f.txt</code>?', ['The shell expands <code>*.c</code> against filenames; grep itself evaluates the regex against text', ['ls and grep each interpret their own pattern', 'For globs the shell expands first, so ls receives plain filenames.'], ['The shell evaluates both', 'The shell only expands globs. Quoted regexes reach grep untouched.'], ['The kernel evaluates both', 'Pattern matching is not a kernel job here.']], 0, 'Globs are shell expansion before the command runs. Regexes are the program\u2019s job.'),
        h.mc('exported variables', 'In a shell you run <code>export A=1</code> and <code>B=2</code>, then start <code>bash</code>. In the child shell, which are set?', [['Both', 'B was never exported, so the child does not inherit it.'], 'Only A', ['Only B', 'It is the exported one that is inherited.'], ['Neither', 'Exported variables are copied into child environments.']], 1, 'Only exported variables are inherited by child processes.')
      ],
      trace: [
        h.trace('glob ?', 'The directory holds <code>lab.c lab0.c lab1.c lab10.c labX.c notes.txt</code>. What does <code>echo lab?.c</code> print?', '', 'lab0.c lab1.c labX.c', '<code>?</code> matches exactly one character: \u201C0\u201D, \u201C1\u201D, \u201CX\u201D. <code>lab.c</code> has none and <code>lab10.c</code> has two.', { verify: { sh: 'touch lab.c lab0.c lab1.c lab10.c labX.c notes.txt\necho lab?.c', expect: ['lab0.c lab1.c labX.c'] } }),
        h.trace('glob class + star', 'Same directory. What does <code>echo lab[01]*.c</code> print? (Names in alphabetical order, space separated.)', '', 'lab0.c lab1.c lab10.c', '<code>[01]</code> is one character, 0 or 1; <code>*</code> then matches any run, including none. lab.c and labX.c fail the <code>[01]</code> position.', { verify: { sh: 'touch lab.c lab0.c lab1.c lab10.c labX.c notes.txt\necho lab[01]*.c', expect: ['lab0.c lab1.c lab10.c'] } }),
        h.trace('overwrite vs append', 'How many lines does <code>f.txt</code> have at the end?', 'echo a >  f.txt\necho b >> f.txt\necho c >  f.txt\necho d >> f.txt\ncat f.txt | grep -c .', '2', 'The third command uses <code>&gt;</code>, which truncates the file, wiping a and b. Then d is appended: the file is c, d.', { verify: { sh: 'echo a > f.txt\necho b >> f.txt\necho c > f.txt\necho d >> f.txt\ncat f.txt | grep -c .', expect: ['2'] } }),
        h.mem('regex', 'With <code>names.txt</code> containing <code>ab_12, ab_123, AB_12, a_1, xyz_99</code> (one per line), which two lines does <code>grep -E \'^[a-z]+_[0-9]{2}$\' names.txt</code> print, in file order?', '', [['first match', 'ab_12'], ['second match', 'xyz_99']], '<code>^[a-z]+</code> is one or more lowercase letters, <code>_</code>, then <b>exactly</b> two digits, then end of line. ab_123 has three digits, AB_12 is uppercase, a_1 has one digit.', { verify: { sh: "printf 'ab_12\\nab_123\\nAB_12\\na_1\\nxyz_99\\n' > names.txt\ngrep -E '^[a-z]+_[0-9]{2}$' names.txt", expect: ['ab_12', 'xyz_99'] } }),
        h.trace('env inheritance', 'What does this print? (Note the exact text.)', 'export A=1\nB=2\nbash -c \'echo "A=$A B=$B"\'', 'A=1 B=', 'The child bash inherits the exported <code>A</code> but not <code>B</code>, which was a plain shell variable. <code>$B</code> expands to nothing.', { verify: { sh: 'export A=1\nB=2\nbash -c \'echo "A=$A B=$B"\'', expect: ['A=1 B='] } }),
        h.trace('${VAR}', 'With <code>NAME=data</code>, what does <code>echo $NAMEfile ${NAME}file</code> print?', '', 'datafile', '<code>$NAMEfile</code> looks up a variable called <code>NAMEfile</code>, which does not exist, so it expands to nothing and vanishes. <code>${NAME}file</code> uses braces to end the name: <code>datafile</code>.', { verify: { sh: 'NAME=data\necho $NAMEfile ${NAME}file', expect: ['datafile'] } })
      ],
      debug: [
        h.bug('overwriting output', 'A script is meant to collect results from two test runs into <code>results.txt</code>, but only the second run\u2019s output is there. Find the root cause.', ['./run_tests         > results.txt', './run_tests --extra > results.txt'], 1,
          [['<code>--extra</code> is not a valid flag', 'The flag is irrelevant to what is lost.'], 'A single <code>&gt;</code> truncates the file, erasing the first run\u2019s output', ['<code>./run_tests</code> needs a full path', 'The ./ is fine for a program in the current directory.']], 1, 'Use <code>&gt;&gt;</code> on the second line to append.'),
        h.bug('overwriting $PATH', 'After sourcing this <code>.bashrc</code>, <code>ls</code> and <code>gcc</code> stop working (\u201Ccommand not found\u201D). Which line is responsible?', ['# ~/.bashrc', 'export PATH="/home/me/bin"', 'alias ll="ls -l"'], 1,
          [['<code>alias</code> must come before <code>export</code>', 'Order of those lines does not matter.'], 'It <b>replaces</b> PATH with a single directory instead of appending to the old value', ['<code>/home/me/bin</code> must end with a slash', 'Trailing slashes do not matter here.']], 1, 'Write <code>export PATH="$PATH:/home/me/bin"</code>. The old value is referenced with <code>$PATH</code> so nothing is lost.'),
        h.fill('pipe', 'Count the lines of <code>log.txt</code> that contain the word <code>error</code>. Fill the operator that sends grep\u2019s output into <code>wc -l</code>.', 'grep error log.txt __0__ wc -l', ['|'], 'The pipe connects grep\u2019s stdout to wc\u2019s stdin, with no temporary file.'),
        h.fill('split streams', 'Send a program\u2019s normal output to <code>out.txt</code> and its error messages to <code>err.txt</code>.', './prog __0__ out.txt __1__ err.txt', ['>', '2>'], '<code>&gt;</code> redirects stdout (fd 1); <code>2&gt;</code> redirects stderr (fd 2).'),
        h.mc('choose the glob', 'Files: <code>a.txt a1.txt a2.txt a10.txt</code>. Which pattern matches <b>exactly</b> <code>a1.txt</code> and <code>a2.txt</code>?', [['<code>a*.txt</code>', 'The star also matches a.txt (empty) and a10.txt.'], '<code>a?.txt</code>', ['<code>a[0-9]*.txt</code>', 'That matches a10.txt too, since the <code>*</code> takes the trailing 0.'], ['<code>a.txt</code>', 'That is a literal name with no wildcard.']], 1, '<code>?</code> demands exactly one character, which rules out a.txt (none) and a10.txt (two).', { verify: { sh: 'touch a.txt a1.txt a2.txt a10.txt\necho a?.txt', expect: ['a1.txt a2.txt'] } })
      ],
      integrate: [
        h.mem('three streams, two files', 'The program <code>p</code> prints <code>ok</code> to stdout and <code>bad</code> to stderr. After <code>./p &gt; out.txt 2&gt; err.txt</code>, what does each file contain? (The terminal shows nothing.)', '', [['out.txt', 'ok'], ['err.txt', 'bad']], 'Each stream was redirected to its own file, so nothing reaches the terminal.', { verify: { sh: CPROG + './p > out.txt 2> err.txt\ncat out.txt\ncat err.txt', expect: ['ok', 'bad'] } }),
        h.mem('pipes only carry stdout', 'Same program <code>p</code>. How many lines does <code>grep -c .</code> count in each case?', '', [['./p 2&gt;&amp;1 | grep -c .', '2'], ['./p | grep -c .', '1']], '<code>2&gt;&amp;1</code> sends stderr to wherever stdout goes (the pipe), so both lines are counted. Without it only stdout enters the pipe; <code>bad</code> goes straight to the terminal.', { verify: { sh: CPROG + './p 2>&1 | grep -c .\n./p 2>/dev/null | grep -c .', expect: ['2', '1'] } }),
        h.trace('pipeline reasoning', 'What does this print?', "printf 'b\\na\\nb\\nc\\na\\n' > in.txt\nsort in.txt | uniq | grep -c .", '3', '<code>sort</code> groups equal lines (a a b b c), <code>uniq</code> collapses adjacent duplicates (a b c), and <code>grep -c .</code> counts the non-empty lines: 3.', { verify: { sh: "printf 'b\\na\\nb\\nc\\na\\n' > in.txt\nsort in.txt | uniq | grep -c .", expect: ['3'] } }),
        h.multi('glob vs regex', 'Select <b>all</b> true statements.', ['The shell expands <code>*.c</code> before <code>ls</code> starts', ['<code>find -name</code> uses regular expressions', '<code>find -name</code> takes a glob pattern, which is why the two are easy to confuse.'], 'In a regex, <code>*</code> quantifies the preceding item; \u201Cany run\u201D needs <code>.*</code>', ['In a glob, <code>+</code> means one or more', 'Globs have no <code>+</code> quantifier; that is regex territory.'], '<code>[a-z]</code> works in both a glob and a regex'], [0, 2, 4], 'Globs are filename expansion by the shell; regexes are matched by a program. They share the character-class syntax but differ in what <code>*</code> means.')
      ],
      produce: [
        h.free('write a pipeline', 'Write a single shell command that prints how many <code>.c</code> files in the current directory contain the word <code>main</code>. Then say, for each part, <b>who</b> processes it (shell or a program) and what it does.',
          '<pre><code>grep -l main *.c | wc -l</code></pre><b>*.c</b> is expanded by the <b>shell</b> into the list of filenames before grep starts. <b>grep -l main</b> prints the <i>names</i> of the files that contain \u201Cmain\u201D, one per line. The <b>|</b> feeds that list to <b>wc -l</b>, which counts the lines, i.e. the files.',
          ['Uses grep (with -l or equivalent) to find files containing the word', 'Uses *.c and recognizes the shell expands it before grep runs', 'Pipes into wc -l (or equivalent) to count', 'Explains what each stage reads (stdin/args) and writes (stdout)'], 3),
        h.explain('glob vs regex', 'Explain the difference between a glob and a regular expression, including who evaluates each and what <code>*</code> means in each.',
          ['A glob matches filenames and is expanded by the shell before the command runs', 'A regex matches text and is evaluated by a program such as grep', 'In a glob, <code>*</code> alone means any run of characters', 'In a regex, <code>*</code> means zero or more of the previous character/group, so \u201Cany run\u201D is <code>.*</code>', 'Regex has more power (quantifiers, anchors); <code>find -name</code> still uses globs'],
          'The shell turns <code>*.c</code> into filenames and the command never sees the pattern. A regex is data the program itself interprets over text. The star is a wildcard in globs but a quantifier in regex.', 4),
        h.explain('$PATH', 'Explain how the shell finds the program when you type <code>foo</code>, why you need <code>./</code> for your own program, and what can go wrong when you edit <code>$PATH</code>.',
          ['The shell searches directories in $PATH, colon-separated, left to right', 'The first match wins, so earlier directories shadow later ones', 'The current directory is not searched by default, so a local program needs ./ to name it explicitly', 'This is a security decision: a malicious file named like a real command could hijack it', 'Assigning PATH without including $PATH replaces it and breaks ordinary commands; append instead'],
          'Command lookup is a left-to-right scan of the directories in $PATH, stopping at the first executable with that name. The current directory is deliberately not on it. Editing PATH must keep the old value (<code>PATH=\u201C$PATH:\u2026\u201D</code>).', 4),
        h.explain('environment variables', 'Explain the difference between a shell variable and an environment variable, and what a child process (like a program you launch) can see.',
          ['A plain assignment (VAR=x) is a shell variable visible only to the current shell', 'export VAR promotes it to an environment variable', 'Child processes inherit a copy of the exported environment', 'Unexported variables do not exist in the child', 'Changes the child makes do not flow back up to the parent'],
          'Exporting marks the variable to be copied into the environment of any process the shell starts. Unexported ones stay local, and a child only ever gets a copy.', 4)
      ]
    }
  });
})();
