/* U08 · Unix basics: terminal/shell/CLI, the file system tree, paths, core file commands, safe deletion
   Sources: CL01 slides (Unix Basics), Dive into Systems 17.1.2, and the concepts practiced in HW00.
   Questions here are original (not copied from graded work); every command answer is verified against real bash. */
(function () {
  var h = Mastery.h;
  /* the lecture's tree, rebuilt under a temp root R so the validator can run real commands */
  var TREE = 'R=$PWD/r; mkdir -p r/home/john/psyc101/notes r/home/carla/comp211/labs r/home/carla/comp211/notes r/home/carla/comp301\n' +
    'touch r/home/john/psyc101/notes/lec{1,2,3}.note r/home/carla/comp211/labs/lab0.c r/home/carla/comp211/notes/lec{1,2}.note\n';
  var STRIP = ' | sed "s#$R##"';
  Mastery.unit({
    id: 'u08', order: 0, title: 'Unix basics: file system, paths & core commands', short: 'Unix file system',
    blurb: 'Terminal vs shell vs CLI, the file system tree, absolute and relative paths, and the everyday commands (pwd, cd, ls, mkdir, touch, cp, mv, rm, rmdir, echo, cat). The foundation for every later shell question.',
    lessons: [{ id: 'l1', label: 'CL01 \u00B7 Unix Basics + RD00' }, { id: 'l9', label: 'HW00 \u00B7 Unix Basics' }],
    learn: {
      big: [
        '<b>Three different things:</b> the <b>CLI</b> is the text-based <i>style</i> of interaction, the <b>terminal</b> is the window that shows text and forwards your keystrokes, and the <b>shell</b> (bash here) is the program that actually interprets and runs your commands.',
        'Terminals came from <b>teletypes</b> typing to a computer; CRT screens replaced the paper, but the name stuck. Terminals stayed because they are <b>scriptable, remote-friendly and powerful</b>.',
        'The file system is a <b>tree</b>. The <b>root</b> <code>/</code> is on top; <b>directories</b> are branches that hold files and other directories; <b>files</b> are the leaves. Every item has a unique <b>absolute path</b> from the root.',
        'A <b>relative path</b> starts from the <b>current working directory</b> (<code>pwd</code> shows it). <code>.</code> is here, <code>..</code> is the parent, <code>~</code> is your home, <code>~name</code> is that user\u2019s home. Plain <code>cd</code> goes home.',
        '<code>cp src dst</code> copies (source stays); <code>mv src dst</code> moves or renames (source is gone). Both take exactly two arguments, and neither changes your working directory.',
        '<b>Deletion is permanent.</b> <code>rm</code> has no recycle bin; <code>rmdir</code> only removes <i>empty</i> directories (a safety net); <code>rm -r</code> recurses and <code>-f</code> silences prompts. Run <code>pwd</code> and <code>ls</code> before any <code>rm -rf</code>.'
      ],
      traps: [
        'Thinking a command moved you. <code>cp</code>, <code>mv</code>, <code>mkdir</code> and <code>touch</code> never change the working directory; only <code>cd</code> does.',
        'Confusing <code>.</code> and <code>..</code>, or forgetting that a path with no leading <code>/</code> is relative to where you <i>are</i>.',
        '<code>mv a b</code> when <code>b</code> is an existing directory puts <code>a</code> <i>inside</i> <code>b</code>; it does not rename or merge.',
        '<code>cp</code> on a directory needs <code>-r</code>. <code>rm</code> on a directory needs <code>-r</code> too (or use <code>rmdir</code> if empty).',
        'Unix names are <b>case sensitive</b>, and spaces in names need escaping or quotes, which is why convention is <code>hello_there</code>.'
      ],
      examples: [
        { kind: 'worked', title: 'Where are you, and what does the tree look like, after these commands? Start in <code>/home/carla</code> (which has <code>comp211</code> and <code>comp301</code>).', code: 'cd comp301\nmkdir labs\nmkdir labs/lab00\ntouch labs/lab00/file1.java\ncd labs/lab00\ncd ..\npwd',
          steps: [
            ['1', '<code>cd comp301</code> \u2192 <code>/home/carla/comp301</code>', 'Relative path: one step down from where you were.'],
            ['2', '<code>mkdir labs</code> and <code>mkdir labs/lab00</code>', 'Creates <code>labs</code>, then <code>lab00</code> inside it. Your location does not change.'],
            ['3', '<code>touch labs/lab00/file1.java</code>', 'An empty file, created via a relative path from comp301.'],
            ['4', '<code>cd labs/lab00</code> \u2192 <code>/home/carla/comp301/labs/lab00</code>', 'Two steps down at once.'],
            ['5', '<code>cd ..</code> \u2192 <code>/home/carla/comp301/labs</code>', '<code>..</code> is the parent of the current directory.'],
            ['6', '<code>pwd</code> prints <code>/home/carla/comp301/labs</code>', 'Always track the cwd line by line.']
          ], takeaway: 'Keep a running \u201Cwhere am I?\u201D after every <code>cd</code>. Only <code>cd</code> moves you; everything else acts relative to where you already are.' },
        { kind: 'complete', item: h.mem('tracking the working directory', 'Continue from <code>/home/carla/comp301/labs</code>. Fill in <code>pwd</code> after each command. (The first is given.)', 'mkdir lab01\ncd ../..\nmkdir temp\ncd ..', [['after mkdir lab01', '/home/carla/comp301/labs', 'given'], ['after cd ../..', '/home/carla'], ['after cd ..', '/home']], '<code>mkdir</code> does not move you. <code>../..</code> goes up two levels (labs, then comp301) to <code>/home/carla</code>. One more <code>..</code> reaches <code>/home</code>.', { verify: { sh: TREE + 'cd r/home/carla/comp301; mkdir labs; cd labs; mkdir lab01\ncd ../..; pwd' + STRIP + '\nmkdir temp; cd ..; pwd' + STRIP, expect: ['/home/carla', '/home'] } }) },
        { kind: 'solo', item: h.mem('copy, rename, list', 'Start with <code>/work/src/main.c</code> and <code>/work/docs</code>, in <code>/work/src</code>. Give the output of each <code>ls</code> (names separated by spaces).', 'mkdir ../out\ncp main.c ../out\nmv main.c util.c\ncd ../out\nls            # first\ncd ..\nls            # second', [['first ls', 'main.c'], ['second ls', 'docs out src']], '<code>cp</code> left a copy of main.c in <code>out</code>; the later <code>mv</code> renamed only the <code>src</code> copy. <code>cd ../out</code> lists that copy (main.c). <code>cd ..</code> lands in <code>/work</code>, which now contains docs, out and src.', { verify: { sh: 'mkdir -p w/work/src w/work/docs; touch w/work/src/main.c; cd w/work/src\nmkdir ../out; cp main.c ../out; mv main.c util.c; cd ../out; echo $(ls); cd ..; echo $(ls)', expect: ['main.c', 'docs out src'] } }) }
      ]
    },
    cards: [
      ['Terminal vs shell vs CLI in one line each?', 'Terminal: the app/window that shows text and sends your keystrokes. Shell: the program that interprets and runs the commands (bash). CLI: the text-based <i>style</i> of interaction.'],
      ['Why does the word \u201Cterminal\u201D still exist?', 'Early teletype terminals were replaced by CRT screens, but the name stuck even though the technology changed.'],
      ['Why do programmers still use the terminal?', 'It is scriptable, works well remotely, and is extremely powerful. Servers often have no GUI at all.'],
      ['What does the shell prompt mean?', 'The shell saying \u201CI\u2019m ready for a command.\u201D The loop is: prompt, you type, Enter, text output, prompt again.'],
      ['What is the root directory, on Mac/Linux and on Windows?', '<code>/</code> on Mac/Linux; a drive letter like <code>C:\\</code> on Windows. It is the top of the file-system tree.'],
      ['Directories vs files in the tree?', 'Directories are branches (they contain files and other directories). Files are the leaves and hold data.'],
      ['What do <code>pwd</code>, <code>cd</code>, <code>ls</code> do?', 'pwd: print the current working directory. cd: change it (no argument = home). ls: list the cwd, or the directory you name.'],
      ['What do <code>.</code>, <code>..</code>, <code>~</code> and <code>~sarita</code> mean?', 'Current directory, parent directory, your home directory, and sarita\u2019s home directory.'],
      ['How do you see hidden files, and what makes a file hidden?', '<code>ls -a</code>. A name beginning with a dot (<code>.git</code>, <code>.vscode</code>, <code>.bashrc</code>) is hidden; it also shows <code>.</code> and <code>..</code>.'],
      ['<code>cp</code> vs <code>mv</code>?', 'cp duplicates (the original stays); mv relocates or renames (the original is gone). Both take source then destination. Neither changes your cwd.'],
      ['How do you copy a whole directory?', '<code>cp -r source_dir dest_dir</code>. Without <code>-r</code> cp refuses a directory.'],
      ['<code>rm</code> vs <code>rmdir</code> vs <code>rm -r</code> vs <code>rm -rf</code>?', 'rm deletes a file permanently (no recycle bin). rmdir deletes only an <i>empty</i> directory. rm -r deletes a directory and everything inside. -f suppresses all prompting.'],
      ['What should you do before running <code>rm -rf</code>?', 'Run <code>pwd</code> and <code>ls</code> to confirm you are in the right directory and see what you are about to destroy. (<code>rm -i</code> prompts first, and some admins alias rm to it.)'],
      ['Which command shows a file\u2019s contents, appends text to one, and counts it?', '<code>cat file</code> shows it. <code>echo "text" &gt;&gt; file</code> appends. <code>wc file</code> counts lines, words and bytes.'],
      ['Naming rules worth remembering?', 'Names are case sensitive (<code>basics</code> \u2260 <code>Basics</code>). Spaces need escaping or quotes, so convention avoids them: <code>hello_there</code>.']
    ],
    tiers: {
      recognize: [
        h.mc('shell vs terminal', 'You open Terminal.app on a Mac and type <code>ls</code>. Which component actually interprets and runs that command?', ['The shell (for example bash)', ['Terminal.app', 'The terminal only displays text and forwards your keystrokes to the shell.'], ['The CLI', 'A CLI is the interaction <i>style</i>, not a program that runs anything.'], ['The file system', 'The file system stores files; it does not interpret commands.']], 0, 'Terminal \u2192 shell \u2192 your command. The shell is the interpreter.'),
        h.mc('why \u201Cterminal\u201D', 'CRT screens replaced paper teletypes. Why is the window you type into still called a \u201Cterminal\u201D?', ['The name stuck even though the technology changed', ['CRTs were manufactured by a company called Terminal', 'The word is historical, not a brand.'], ['It terminates your programs', 'It refers to being the end point connected to the computer.'], ['It is the last program run at shutdown', 'The name has nothing to do with program order.']], 0, 'Teletype and console terminals connected to computers; CRTs kept the word.'),
        h.mc('file vs directory', 'In the file-system tree, which items can <b>contain other items</b>?', ['Directories (folders)', ['Files', 'Files are leaves: they hold data and contain nothing else.'], ['Both equally', 'Only directories hold other items.'], ['Only the root', 'Any directory can contain files and subdirectories.']], 0, 'Directories are branches; files are the leaves.'),
        h.mc('rename correctly', 'You want to rename <code>report.txt</code> to <code>report_final.txt</code> without keeping the old name. Which command does that?', ['<code>mv report.txt report_final.txt</code>', ['<code>cp report.txt report_final.txt</code>', 'That leaves <code>report.txt</code> in place: a copy, not a rename.'], ['<code>mv report_final.txt report.txt</code>', 'The arguments are reversed (source first, then destination).'], ['<code>rm report.txt report_final.txt</code>', 'That would just delete files.']], 0, 'mv with source then destination both moves and renames.'),
        h.multi('deleting', 'Select <b>all</b> true statements about removing things in Unix.', ['<code>rm</code> permanently deletes a file; there is no recycle bin', '<code>rmdir</code> refuses to remove a directory that still has contents', ['<code>rmdir</code> can delete a non-empty directory if you add <code>-f</code>', 'rmdir has no such option; use <code>rm -r</code> (deliberately).'], '<code>rm -r</code> removes a directory and everything inside it', 'Running <code>pwd</code> and <code>ls</code> before <code>rm -rf</code> is good practice'], [0, 1, 3, 4], 'rmdir\u2019s refusal is a safety net, and rm -rf is the deliberate escape hatch. Check where you are first.'),
        h.mc('case sensitivity', 'A directory contains a file named <code>basics</code>. Which statement is true?', ['<code>Basics</code> would be a different file, so both can exist', ['<code>Basics</code> refers to the same file', 'Unix file names are case sensitive.'], ['Capital letters are not allowed in file names', 'They are allowed; names are just case sensitive.'], ['The shell converts everything to lowercase', 'It does not; case is preserved and significant.']], 0, 'basics and Basics are two separate names.')
      ],
      trace: [
        h.trace('following cd', 'You start in <code>/home/carla</code>. After <code>cd comp211/labs</code>, then <code>cd ../notes</code>, then <code>cd ../..</code>, what does <code>pwd</code> print?', '', '/home/carla', '<code>comp211/labs</code> \u2192 <code>.../comp211/labs</code>; <code>../notes</code> goes up to comp211 and down into notes; <code>../..</code> goes up two levels: notes \u2192 comp211 \u2192 carla.', { verify: { sh: TREE + 'cd r/home/carla\n(cd comp211/labs; cd ../notes; cd ../..; pwd)' + STRIP, expect: ['/home/carla'] } }),
        h.mem('ls with an argument', 'You are in <code>/home/carla</code>. What do these print? (Names separated by spaces.)', '', [['ls comp211', 'labs notes'], ['ls comp211/notes', 'lec1.note lec2.note']], '<code>ls</code> with a path lists that directory without moving you there.', { verify: { sh: TREE + 'cd r/home/carla; echo $(ls comp211); echo $(ls comp211/notes)', expect: ['labs notes', 'lec1.note lec2.note'] } }),
        h.mem('build, copy, rename', 'You start in <code>/home/carla</code>. After this sequence, fill in the results.', 'cd comp211\nmkdir build\ntouch build/a.o\ncd build\nmkdir ../out\ncp a.o ../out\nmv a.o b.o\ncd ..', [['pwd', '/home/carla/comp211'], ['ls build', 'b.o'], ['ls out', 'a.o'], ['ls (no argument)', 'build labs notes out']], 'The last <code>cd ..</code> leaves you in comp211. build now holds the renamed b.o; out holds the earlier copy a.o; comp211 now has build and out alongside labs and notes.', { verify: { sh: TREE + 'cd r/home/carla\ncd comp211; mkdir build; touch build/a.o; cd build; mkdir ../out; cp a.o ../out; mv a.o b.o; cd ..\npwd' + STRIP + '\necho $(ls build); echo $(ls out); echo $(ls)', expect: ['/home/carla/comp211', 'b.o', 'a.o', 'build labs notes out'] } }),
        h.mem('cp vs mv', 'From <code>/home/carla/comp211</code> you run <code>cp notes/lec1.note ../comp301</code> and then <code>mv notes/lec2.note ../comp301</code>. Fill in the results.', '', [['ls notes', 'lec1.note'], ['ls ../comp301', 'lec1.note lec2.note'], ['pwd', '/home/carla/comp211']], 'cp left lec1.note in notes and added a copy to comp301. mv took lec2.note out of notes. Neither command moved you.', { verify: { sh: TREE + 'cd r/home/carla/comp211\ncp notes/lec1.note ../comp301; mv notes/lec2.note ../comp301\necho $(ls notes); echo $(ls ../comp301); pwd' + STRIP, expect: ['lec1.note', 'lec1.note lec2.note', '/home/carla/comp211'] } }),
        h.mem('hidden files', 'In an empty directory you run <code>touch .secret visible</code>. What do the two listings print? (Names in order, separated by spaces.)', '', [['ls', 'visible'], ['ls -a', '. .. .secret visible']], 'A name starting with a dot is hidden from plain <code>ls</code>. <code>ls -a</code> shows everything, including <code>.</code> and <code>..</code>.', { verify: { sh: 'mkdir t; cd t; touch .secret visible; echo $(ls); echo $(ls -a)', expect: ['visible', '. .. .secret visible'] } }),
        h.mem('rmdir is a safety net', 'You run <code>mkdir d; touch d/f</code>. Does <code>rmdir d</code> work now? After <code>rm d/f</code>, does <code>rmdir d</code> work? (Answer \u201Cworks\u201D or \u201Cfails\u201D.)', '', [['rmdir d (d still holds f)', 'fails'], ['rmdir d (after rm d/f)', 'works']], 'rmdir only removes <i>empty</i> directories. That refusal protects content you forgot was inside.', { verify: { sh: 'mkdir d; touch d/f; rmdir d 2>/dev/null && echo works || echo fails; rm d/f; rmdir d 2>/dev/null && echo works || echo fails', expect: ['fails', 'works'] } }),
        h.trace('echo, append, count', 'How many lines does <code>basics</code> contain at the end?', 'touch basics\necho "ls: list directory contents" >> basics\necho "cd: change directory" >> basics\ncat basics | grep -c .', '2', '<code>touch</code> makes an empty file; each <code>&gt;&gt;</code> appends one line. <code>cat</code> shows both lines and <code>grep -c .</code> counts the non-empty ones.', { verify: { sh: 'touch basics; echo "ls: list directory contents" >> basics; echo "cd: change directory" >> basics; cat basics | grep -c .', expect: ['2'] } })
      ],
      debug: [
        h.bug('failed cd, then rm -rf', 'A cleanup script is meant to empty the <code>build</code> folder. One day it deleted the <b>whole project</b> instead. Which line is the root cause?', ['cd ~/project/biuld          # typo: folder is "build"', 'rm -rf ./*'], 1,
          [['<code>~</code> should be written as <code>/home</code>', 'Either works; that is not the problem.'], 'The <code>cd</code> failed, so the script stayed in its old directory and <code>rm -rf ./*</code> ran there', ['<code>./*</code> only matches hidden files', 'The glob matches ordinary files and directories, which is exactly why it was destructive.']], 1, 'Never run a destructive command after an unchecked <code>cd</code>. Use <code>cd dir &amp;&amp; rm -rf ./*</code> so the delete only runs if the <code>cd</code> succeeded, and check <code>pwd</code> first.', { hint: 'What does the second line do if the first one does not change directory?' }),
        h.bug('copying a directory', '<code>cp unix_notes notes_copy</code> fails with a complaint about omitting a directory. Which part of the command is the problem?', ['mkdir unix_notes', 'cp unix_notes notes_copy'], 1,
          [['The destination must already exist', 'cp creates the destination when copying one source.'], 'It is missing <code>-r</code>: copying a directory needs the recursive option', ['cp can only copy one file at a time', 'It can copy many; the issue is that the source is a directory.']], 1, '<code>cp -r unix_notes notes_copy</code> copies the directory and its whole contents.'),
        h.fill('relative paths', 'You are in <code>/work/src</code>. The tree has <code>/work/src/main.c</code>, <code>/work/docs/notes.md</code> and <code>/work/tmp/</code>. Fill the blanks using paths <b>relative</b> to where you are.', 'cp __0__ /work/tmp\nmv main.c __1__\nls __2__', ['../docs/notes.md', 'app.c', '../docs'], 'From src, the docs directory is a sibling: go up with <code>..</code> then down into docs. Renaming is <code>mv old new</code>.', { verify: { sh: 'mkdir -p w/work/src w/work/docs w/work/tmp; touch w/work/src/main.c w/work/docs/notes.md; cd w/work/src\ntest -e ../docs/notes.md && echo ../docs/notes.md; mv main.c app.c && echo app.c; ls ../docs >/dev/null && echo ../docs', expect: ['../docs/notes.md', 'app.c', '../docs'] } }),
        h.parsons('building a project folder', 'Arrange the commands so that <code>main.c</code> ends up inside <code>proj/src</code>, starting from an empty directory. Two commands do not belong.', ['mkdir proj', 'cd proj', 'mkdir src', 'touch src/main.c', 'ls src'], ['cd main.c', 'rmdir proj'], '<code>proj</code> must exist before you <code>cd</code> into it, and <code>src</code> before you put a file in it. <code>cd main.c</code> fails (main.c is a file) and rmdir would delete what you are building.')
      ],
      integrate: [
        h.mem('writing relative paths', 'The tree is <code>/lab/x/y/data.txt</code>, <code>/lab/x/notes.txt</code> and <code>/lab/z/out.log</code>. Write the <b>relative path</b> that names the target from each starting directory.', '', [['from /lab/x/y to out.log', '../../z/out.log'], ['from /lab/z to data.txt', '../x/y/data.txt'], ['from /lab/x to out.log', '../z/out.log']], 'Go up with <code>..</code> to the lowest common directory (<code>/lab</code>), then down. From y: up to x, up to lab, down into z. From z: up to lab, down x, y. From x: up to lab, down z.', { verify: { sh: 'mkdir -p r/lab/x/y r/lab/z; touch r/lab/x/y/data.txt r/lab/x/notes.txt r/lab/z/out.log\n(cd r/lab/x/y; ls ../../z/out.log); (cd r/lab/z; ls ../x/y/data.txt); (cd r/lab/x; ls ../z/out.log)', expect: ['../../z/out.log', '../x/y/data.txt', '../z/out.log'] } }),
        h.mem('home, parent, and cd with no argument', 'Your home is <code>/home/carla</code> and you start in <code>/home/carla/comp211/labs</code>. Fill in <code>pwd</code> after each command in sequence.', 'cd\ncd ~/comp301\ncd ../comp211/notes\ncd ../../..', [['after cd', '/home/carla'], ['after cd ~/comp301', '/home/carla/comp301'], ['after cd ../comp211/notes', '/home/carla/comp211/notes'], ['after cd ../../..', '/home']], '<code>cd</code> with no argument goes home. <code>~</code> expands to the home directory. <code>../comp211/notes</code> goes up from comp301 to carla, then down. Three <code>..</code> from notes climb notes \u2192 comp211 \u2192 carla \u2192 home.', { verify: { sh: TREE + 'export HOME=$R/home/carla; cd $R/home/carla/comp211/labs\ncd; pwd' + STRIP + '\ncd ~/comp301; pwd' + STRIP + '\ncd ../comp211/notes; pwd' + STRIP + '\ncd ../../..; pwd' + STRIP, expect: ['/home/carla', '/home/carla/comp301', '/home/carla/comp211/notes', '/home'] } }),
        h.mem('mv into an existing directory', 'In an empty directory you run <code>mkdir a b</code>, <code>touch a/f</code>, then <code>mv a b</code>. What do these list?', '', [['ls b', 'a'], ['ls b/a', 'f']], 'Because <code>b</code> already exists as a directory, <code>mv a b</code> moves <code>a</code> <i>into</i> it (making <code>b/a</code>); it does not rename or merge.', { verify: { sh: 'mkdir t; cd t; mkdir a b; touch a/f; mv a b; echo $(ls b); echo $(ls b/a)', expect: ['a', 'f'] } }),
        h.multi('putting commands together', 'You are in <code>/home/jake/comp211/labs/lab00</code>, which holds <code>file1.c</code> and <code>file2.c</code>. You want both files moved up into <code>labs</code>, then <code>lab00</code> removed. Select <b>all</b> command sequences that work.', ['<code>mv file1.c file2.c ..</code> then <code>cd ..</code> then <code>rmdir lab00</code>', ['<code>rmdir lab00</code> then <code>mv file1.c file2.c ..</code>', 'You are inside lab00, and rmdir would fail on a non-empty directory (and on the one you are standing in).'], ['<code>cp file1.c file2.c ..</code> then <code>rmdir lab00</code>', 'cp leaves the originals, so lab00 is still not empty and rmdir fails.'], '<code>mv file1.c file2.c ../</code> then <code>cd ..</code> then <code>rm -r lab00</code>'], [0, 3], 'You must first empty lab00 (mv, not cp), then leave it, then remove it. rmdir needs it empty; rm -r works either way.',
          { verify: { sh: 'mkdir -p a/labs/lab00; touch a/labs/lab00/file1.c a/labs/lab00/file2.c; (cd a/labs/lab00; mv file1.c file2.c ..; cd ..; rmdir lab00 && echo ok0 || echo no0)\nmkdir -p b/labs/lab00; touch b/labs/lab00/file1.c b/labs/lab00/file2.c; (cd b/labs/lab00; rmdir ../lab00 2>/dev/null && echo ok1 || echo no1)\nmkdir -p c/labs/lab00; touch c/labs/lab00/file1.c c/labs/lab00/file2.c; (cd c/labs/lab00; cp file1.c file2.c ..; cd ..; rmdir lab00 2>/dev/null && echo ok2 || echo no2)\nmkdir -p d/labs/lab00; touch d/labs/lab00/file1.c d/labs/lab00/file2.c; (cd d/labs/lab00; mv file1.c file2.c ../; cd ..; rm -r lab00 && echo ok3 || echo no3)', expect: ['ok0', 'no1', 'no2', 'ok3'] } })
      ],
      produce: [
        h.free('commands from a tree', 'The tree is <code>/home/sam/classes/COMP211/notes.txt</code>, <code>/home/sam/letters/draft.txt</code>, <code>/home/sam/projects/demo.c</code>, and you are in <code>/home/sam/classes/COMP211</code>. Write commands for each task, then redo the first two using <b>absolute</b> paths and say when you would prefer each style. (1) show the contents of <code>demo.c</code>; (2) copy <code>notes.txt</code> into <code>letters</code>; (3) remove <code>letters</code> only if it is empty; (4) create a new directory <code>archive</code> in <code>projects</code>.',
          '(1) <code>cat ../../projects/demo.c</code> \u00B7 abs: <code>cat /home/sam/projects/demo.c</code><br>(2) <code>cp notes.txt ../../letters</code> \u00B7 abs: <code>cp /home/sam/classes/COMP211/notes.txt /home/sam/letters</code><br>(3) <code>rmdir ../../letters</code> (rmdir refuses non-empty directories, so it is the safe choice; letters still holds draft.txt so this would fail)<br>(4) <code>mkdir ../../projects/archive</code><br>Relative paths are shorter and work well when you are already nearby; absolute paths are unambiguous and safer in scripts or when you are not sure where you are.',
          ['Uses <code>../..</code> correctly to reach <code>/home/sam</code> from COMP211', 'Uses <code>cp</code> (not <code>mv</code>) for the copy and a correct destination', 'Uses <code>rmdir</code> (not <code>rm -rf</code>) for \u201Conly if empty\u201D', 'Gives correct absolute-path versions', 'States a sensible trade-off between relative and absolute paths'], 4),
        h.explain('terminal, shell, CLI', '<b>Teach it.</b> Explain the difference between a terminal, a shell and a CLI, and describe what happens, step by step, between typing <code>ls</code> and seeing the output.',
          ['The CLI is the text-based interface style, not one program', 'The terminal is the app/window that displays text and forwards keystrokes', 'The shell (bash) is the program that interprets and runs the command', 'Flow: prompt appears, you type, press Enter, the shell runs it, text output returns, prompt appears again', 'The terminal and shell are separate programs (you can run different shells in the same terminal)'],
          'The terminal is just the window. When you press Enter, it hands your line to the shell, which parses it and runs <code>ls</code>. The output text is passed back and the terminal displays it. CLI describes this whole text-command style.', 4),
        h.explain('paths', 'Explain absolute vs relative paths, what <code>.</code>, <code>..</code> and <code>~</code> mean, and what \u201Ccurrent working directory\u201D has to do with all of it.',
          ['The current working directory (cwd) is where the user is operating; relative paths and default file operations are interpreted from it', 'An absolute path starts at the root <code>/</code> and means the same thing from anywhere', 'A relative path starts from the cwd and changes meaning when the cwd changes', '<code>.</code> is the current directory, <code>..</code> the parent, <code>~</code> your home (and plain cd returns home)', 'New files without a path are created in the cwd'],
          'Everything is interpreted relative to the cwd unless the path starts with <code>/</code>. <code>..</code> climbs one level; <code>~</code> jumps to home. That is why the same relative path can name different files depending on where you are.', 4),
        h.explain('safe deleting', 'Explain how <code>rm</code> and <code>rmdir</code> differ, why Unix deletion deserves care, and the habits that keep you from destroying the wrong files.',
          ['rm permanently deletes files; there is no recycle bin', 'rmdir only removes empty directories, which prevents accidentally deleting unseen content', 'rm -r removes directories recursively; -f suppresses prompts; rm -rf is the most dangerous combination', 'Run pwd and ls first to confirm the location and contents', 'rm -i prompts before each deletion, so some systems alias rm to it'],
          'Because nothing goes to a trash, a mistake is permanent. rmdir\u2019s restriction is deliberate friction. When you do need rm -rf, confirm where you are and what is there first, or use -i.', 4)
      ]
    }
  });
})();
